/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.CitemSearch;
import Controller.CitemSales;
import com.mysql.cj.protocol.Resultset;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author thara
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    int x,y;
    public Sales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbl_close = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_min = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txt_uprice = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_qty = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_tot = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_cash = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_balance = new javax.swing.JTextField();
        btn_sell = new javax.swing.JButton();
        btn_clr = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(870, 629));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(239, 243, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(870, 629));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 102));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/logo.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 211, 61));

        lbl_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/close new.png"))); // NOI18N
        lbl_close.setText("jLabel2");
        lbl_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_closeMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_close, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 20, 30, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sales");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 18, 403, 37));

        lbl_min.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/minimize new.png"))); // NOI18N
        lbl_min.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_minMouseClicked(evt);
            }
        });
        jPanel2.add(lbl_min, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 20, -1, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 70));

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setForeground(new java.awt.Color(0, 0, 102));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 1080, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Item ID");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, -1, 30));

        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_idKeyReleased(evt);
            }
        });
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 400, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Name");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, -1, -1));

        txt_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 400, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setText("Unit Price");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, -1, 30));

        txt_uprice.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txt_uprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 400, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Quantity");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, -1, 30));

        txt_qty.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_qty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_qtyKeyReleased(evt);
            }
        });
        jPanel1.add(txt_qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 400, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Total Price");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, -1, 40));

        txt_tot.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txt_tot, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 400, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Cash");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, -1, 40));

        txt_cash.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txt_cash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_cashKeyReleased(evt);
            }
        });
        jPanel1.add(txt_cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, 400, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Balance");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, 30));

        txt_balance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.add(txt_balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 450, 400, -1));

        btn_sell.setBackground(new java.awt.Color(0, 153, 51));
        btn_sell.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sell.setForeground(new java.awt.Color(255, 255, 255));
        btn_sell.setText("Sell");
        btn_sell.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sellMouseClicked(evt);
            }
        });
        btn_sell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sellActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sell, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 90, -1));

        btn_clr.setBackground(new java.awt.Color(0, 0, 102));
        btn_clr.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_clr.setForeground(new java.awt.Color(255, 255, 255));
        btn_clr.setText("Clear");
        btn_clr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clrMouseClicked(evt);
            }
        });
        jPanel1.add(btn_clr, new org.netbeans.lib.awtextra.AbsoluteConstraints(607, 520, 90, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/picture12.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 220, 160));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/picture6.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 220, 160));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/img/picture7.jpg"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 220, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_closeMouseClicked
      
       dispose();
       
    }//GEN-LAST:event_lbl_closeMouseClicked

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void btn_sellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sellActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_sellActionPerformed

    private void txt_idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_idKeyReleased
       try{  
        String Id;
            Id=txt_id.getText();

            CitemSearch is=new CitemSearch();
            ResultSet rst=is.CsearchItem(Id);
            if(rst.next())
            {
            
                txt_name.setText(rst.getString(1));
                 txt_uprice.setText(String.valueOf(rst.getDouble(2)));
            }
            
                    
        
       }
       catch(SQLException e)
       {
           System.err.println(e.getMessage());
       }
    }//GEN-LAST:event_txt_idKeyReleased

    private void txt_qtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_qtyKeyReleased
       Double uprice=Double.parseDouble(txt_uprice.getText());
       int quantity=Integer.parseInt(txt_qty.getText());
       Double totp=uprice*quantity;
       txt_tot.setText(totp+"");
    }//GEN-LAST:event_txt_qtyKeyReleased

    private void txt_cashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_cashKeyReleased
        int cash=Integer.parseInt(txt_cash.getText());
        Double totp=Double.parseDouble(txt_tot.getText());
        Double balance=cash-totp;
        txt_balance.setText(balance+"");
    }//GEN-LAST:event_txt_cashKeyReleased

    private void btn_clrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clrMouseClicked
        txt_id.setText("");
        txt_name.setText("");
        txt_uprice.setText("");
        txt_qty.setText("");
        txt_tot.setText("");
        txt_cash.setText("");
        txt_balance.setText("");
    }//GEN-LAST:event_btn_clrMouseClicked

    private void btn_sellMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sellMouseClicked
        try{ Double Uprice,totprice,balance;
             String id,name,category;
             int Qty,cash;
        
        id=txt_id.getText();
        name=txt_name.getText();
        Uprice=Double.parseDouble(txt_uprice.getText());
        Qty=Integer.parseInt(txt_qty.getText());
        totprice=Double.parseDouble(txt_tot.getText());
        cash=Integer.parseInt(txt_cash.getText());
        balance=Double.parseDouble(txt_balance.getText());
        
         if (id.isEmpty()) 
       {
        JOptionPane.showMessageDialog(null, "Please enter ID");
       } 
       
       else if ( Qty <= 0) 
        {
        JOptionPane.showMessageDialog(null, "Please enter a valid quantity");
        } 
      
       else if ( cash <= 0) 
        {
        JOptionPane.showMessageDialog(null, "Please enter a valid cash");
        } 
       
       else {
        
       
        
        CitemSales ci=new CitemSales();
        ci.CsaleItems(id, name, totprice, Qty, totprice, cash, balance);
        
         txt_id.setText("");
        txt_name.setText("");
        txt_uprice.setText("");
        txt_qty.setText("");
        txt_tot.setText("");
        txt_cash.setText("");
        txt_balance.setText("");
       }
    }
    catch (NumberFormatException ex) 
    {
    JOptionPane.showMessageDialog(null, "Please enter quantity & cash Numbers only!");
    } 
    catch (Exception ex) 
    {
    JOptionPane.showMessageDialog(null, "Please try again");
    ex.printStackTrace(); // 
    }
        
    }//GEN-LAST:event_btn_sellMouseClicked

    private void lbl_minMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_minMouseClicked
        this.setExtendedState(Sales.ICONIFIED);
    }//GEN-LAST:event_lbl_minMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_clr;
    private javax.swing.JButton btn_sell;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbl_close;
    private javax.swing.JLabel lbl_min;
    private javax.swing.JTextField txt_balance;
    private javax.swing.JTextField txt_cash;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_qty;
    private javax.swing.JTextField txt_tot;
    private javax.swing.JTextField txt_uprice;
    // End of variables declaration//GEN-END:variables
}
